name: 'user-web'
port: 9000

userSrv:
  host: '127.0.0.1'
  port: 50051
  name: 'user-srv'

jwt:
  key: "3WEraPIv!myZlYR&vQzoCMx5RtX3uhgL"

consul:
  host: '192.168.0.101'
  port: 8500

#host: '127.0.0.1'
#port: 8848
#namespace: 'c1872978-d51c-4188-a497-4e0cd20b97d5'
#user: 'nacos'
#password: 'nacos'
#dataid: 'user-web.json'
#group: 'pro'